# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'pathname'

module TestData
  ROOT = Pathname.new(__FILE__).parent.join('data')
  INPUT_ROOT = ROOT.join('input')
  DEST_ROOT = ROOT.join('dest')

  def test_input(path)
    INPUT_ROOT.join(path)
  end

  def test_dest(path)
    DEST_ROOT.join(path)
  end

  def self.prepare_dest
    DEST_ROOT.mkpath
  end

  def self.clean_dest
    DEST_ROOT.rmtree
  end
end

RSpec.configure do |config|
  # Limit the spec run to only specs with the focus metadata. If no specs have
  # the filtering metadata and `run_all_when_everything_filtered = true` then
  # all specs will run.
  #config.filter_run :focus

  # Run all specs when none match the provided filter. This works well in
  # conjunction with `config.filter_run :focus`, as it will run the entire
  # suite when no specs have `:filter` metadata.
  #config.run_all_when_everything_filtered = true

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  #config.order = 'random'

  config.include TestData
  config.before(:each) do
    TestData.prepare_dest
  end
  config.after(:each) do
    TestData.clean_dest
  end
end
